version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: ilitvih/kittygram_backend # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
  frontend:
    image: ilitvih/kittygram_frontend  # Качаем с Docker Hub
    build: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: ilitvih/kittygram_gateway  # Качаем с Docker Hub
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/staticfileskitty
      - media:/var/www/media
    depends_on:
      - backend